name: CI for Terraform

on:
  workflow_dispatch:

jobs:        
  Checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: pip install checkov

      - name: Checkov version
        run: checkov --version

      - name: Run Checkov
        run: checkov -d .
        continue-on-error: true
        
  TFSec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install tfsec
        run: |
          VERSION=$(curl -s https://api.github.com/repos/aquasecurity/tfsec/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
          curl -Lo tfsec https://github.com/aquasecurity/tfsec/releases/download/${VERSION}/tfsec-linux-amd64
          chmod +x tfsec
          sudo mv tfsec /usr/local/bin/

      - name: Run tfsec
        run: tfsec .
        continue-on-error: true
